import type { LucideIcon } from "lucide-react";
import {
  HardHat,
  Droplets,
  Landmark,
  School,
  Users,
  Globe,
  BookOpen,
  HeartPulse,
  HandHeart,
  LifeBuoy,
  Sprout,
  ClipboardList,
  CheckCircle,
  FileCheck,
  Shield,
  Eye,
  FileText,
  Award,
  Stamp,
  Home,
  Building2,
  Church,
  Hospital,
  GraduationCap,
  Baby,
  Heart,
  Handshake,
  Gift,
  Coins,
  Wallet,
  PiggyBank,
  Truck,
  Package,
  ShoppingCart,
  Store,
  Factory,
  Hammer,
  Wrench,
  Construction,
  MapPin,
  Map,
  Compass,
  Navigation,
  Plane,
  Ship,
  Car,
  Bus,
  Train,
  TreePine,
  Leaf,
  Flower2,
  Sun,
  CloudRain,
  Flame,
  Zap,
  Lightbulb,
  Target,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Calendar,
  Clock,
  Timer,
  Bell,
  Mail,
  Phone,
  MessageCircle,
  MessagesSquare,
  Video,
  Camera,
  Image,
  Images,
  Play,
  Music,
  Mic,
  Radio,
  Tv,
  Wifi,
  Smartphone,
  Laptop,
  Monitor,
  Printer,
  FolderOpen,
  File,
  Files,
  Archive,
  Bookmark,
  Tag,
  Tags,
  Search,
  Settings,
  SlidersHorizontal,
  Lock,
  Key,
  UserCheck,
  UserPlus,
  UsersRound,
  Crown,
  Star,
  Sparkles,
  ThumbsUp,
  Smile,
  PartyPopper,
  Trophy,
  Medal,
  Flag,
  Megaphone,
  Volume2,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle2,
  XCircle,
  PlusCircle,
  MinusCircle,
  ArrowRight,
  ExternalLink,
  Download,
  Upload,
  Share2,
  Link,
  Globe2,
  Earth,
  Languages,
  BookMarked,
  Library,
  PenLine,
  Pencil,
  Edit,
  Trash2,
  Recycle,
  RefreshCw,
  RotateCw,
  Scale,
  Gavel,
  Briefcase,
  ClipboardCheck,
  ListChecks,
  LayoutGrid,
  Layers,
  Box,
  Boxes,
  Utensils,
  Coffee,
  Apple,
  Wheat,
  Milk,
  Stethoscope,
  Pill,
  Syringe,
  Accessibility,
  PersonStanding,
  Footprints,
  Mountain,
  Waves,
  Droplet,
  CloudSun,
  Umbrella,
  Tent,
} from "lucide-react";

export type IconCatalogEntry = {
  icon: LucideIcon;
  label: string;
  category: string;
};

/** فهرس شامل للأيقونات — key يُحفظ في Firestore */
export const iconCatalog: Record<string, IconCatalogEntry> = {
  // — تنمية وبنية —
  projects: { icon: HardHat, label: "مشاريع / إنشاءات", category: "تنمية" },
  construction: { icon: Construction, label: "بناء", category: "تنمية" },
  hammer: { icon: Hammer, label: "أدوات", category: "تنمية" },
  wrench: { icon: Wrench, label: "صيانة", category: "تنمية" },
  factory: { icon: Factory, label: "مصنع", category: "تنمية" },
  home: { icon: Home, label: "منازل", category: "تنمية" },
  building: { icon: Building2, label: "مباني", category: "تنمية" },
  landmark: { icon: Landmark, label: "معالم / مساجد", category: "تنمية" },
  church: { icon: Church, label: "ديني", category: "تنمية" },
  mosques: { icon: Landmark, label: "مساجد", category: "تنمية" },
  // — مياه وطبيعة —
  wells: { icon: Droplets, label: "آبار مياه", category: "طبيعة" },
  droplet: { icon: Droplet, label: "قطرة ماء", category: "طبيعة" },
  waves: { icon: Waves, label: "مياه", category: "طبيعة" },
  tree: { icon: TreePine, label: "بيئة", category: "طبيعة" },
  leaf: { icon: Leaf, label: "زراعة", category: "طبيعة" },
  flower: { icon: Flower2, label: "زهور", category: "طبيعة" },
  sun: { icon: Sun, label: "طاقة شمسية", category: "طبيعة" },
  cloudRain: { icon: CloudRain, label: "مطر", category: "طبيعة" },
  mountain: { icon: Mountain, label: "جبال", category: "طبيعة" },
  tent: { icon: Tent, label: "مخيمات", category: "طبيعة" },
  // — تعليم —
  schools: { icon: School, label: "مدارس", category: "تعليم" },
  education: { icon: BookOpen, label: "تعليم", category: "تعليم" },
  gradCap: { icon: GraduationCap, label: "تخرج", category: "تعليم" },
  library: { icon: Library, label: "مكتبة", category: "تعليم" },
  bookMarked: { icon: BookMarked, label: "كتب", category: "تعليم" },
  penLine: { icon: PenLine, label: "كتابة", category: "تعليم" },
  languages: { icon: Languages, label: "لغات", category: "تعليم" },
  // — صحة —
  health: { icon: HeartPulse, label: "صحة", category: "صحة" },
  hospital: { icon: Hospital, label: "مستشفى", category: "صحة" },
  stethoscope: { icon: Stethoscope, label: "طب", category: "صحة" },
  pill: { icon: Pill, label: "دواء", category: "صحة" },
  syringe: { icon: Syringe, label: "تطعيم", category: "صحة" },
  accessibility: { icon: Accessibility, label: "إتاحة", category: "صحة" },
  // — إنسانية —
  beneficiaries: { icon: Users, label: "مستفيدون", category: "إنسانية" },
  users: { icon: UsersRound, label: "مجتمع", category: "إنسانية" },
  orphans: { icon: HandHeart, label: "أيتام", category: "إنسانية" },
  baby: { icon: Baby, label: "أطفال", category: "إنسانية" },
  heart: { icon: Heart, label: "رعاية", category: "إنسانية" },
  relief: { icon: LifeBuoy, label: "إغاثة", category: "إنسانية" },
  community: { icon: Sprout, label: "مجتمع محلي", category: "إنسانية" },
  handshake: { icon: Handshake, label: "شراكة", category: "إنسانية" },
  gift: { icon: Gift, label: "هبات", category: "إنسانية" },
  person: { icon: PersonStanding, label: "فرد", category: "إنسانية" },
  footprints: { icon: Footprints, label: "زيارات", category: "إنسانية" },
  // — تمويل —
  coins: { icon: Coins, label: "تمويل", category: "تمويل" },
  wallet: { icon: Wallet, label: "محفظة", category: "تمويل" },
  piggyBank: { icon: PiggyBank, label: "ادخار", category: "تمويل" },
  trendUp: { icon: TrendingUp, label: "نمو", category: "تمويل" },
  barChart: { icon: BarChart3, label: "إحصائيات", category: "تمويل" },
  pieChart: { icon: PieChart, label: "تحليل", category: "تمويل" },
  // — عمليات —
  study: { icon: ClipboardList, label: "دراسة", category: "عمليات" },
  approve: { icon: CheckCircle, label: "اعتماد", category: "عمليات" },
  execute: { icon: HardHat, label: "تنفيذ", category: "عمليات" },
  report: { icon: FileCheck, label: "تقارير", category: "عمليات" },
  clipboardCheck: { icon: ClipboardCheck, label: "قائمة مهام", category: "عمليات" },
  listChecks: { icon: ListChecks, label: "متابعة", category: "عمليات" },
  target: { icon: Target, label: "أهداف", category: "عمليات" },
  activity: { icon: Activity, label: "نشاط", category: "عمليات" },
  timer: { icon: Timer, label: "جدول زمني", category: "عمليات" },
  calendar: { icon: Calendar, label: "تقويم", category: "عمليات" },
  clock: { icon: Clock, label: "وقت", category: "عمليات" },
  // — تميز —
  transparency: { icon: Shield, label: "شفافية", category: "تميز" },
  followUp: { icon: Eye, label: "متابعة", category: "تميز" },
  reports: { icon: FileText, label: "تقارير", category: "تميز" },
  team: { icon: Users, label: "فريق", category: "تميز" },
  documented: { icon: CheckCircle, label: "موثّق", category: "تميز" },
  quality: { icon: Award, label: "جودة", category: "تميز" },
  trophy: { icon: Trophy, label: "تميز", category: "تميز" },
  medal: { icon: Medal, label: "إنجاز", category: "تميز" },
  star: { icon: Star, label: "نجمة", category: "تميز" },
  sparkles: { icon: Sparkles, label: "تميز", category: "تميز" },
  thumbsUp: { icon: ThumbsUp, label: "رضا", category: "تميز" },
  // — وثائق —
  registration: { icon: FileText, label: "تسجيل", category: "وثائق" },
  licenses: { icon: Stamp, label: "تراخيص", category: "وثائق" },
  endorsements: { icon: Award, label: "اعتمادات", category: "وثائق" },
  annualReports: { icon: BookOpen, label: "تقارير سنوية", category: "وثائق" },
  file: { icon: File, label: "ملف", category: "وثائق" },
  files: { icon: Files, label: "ملفات", category: "وثائق" },
  folder: { icon: FolderOpen, label: "مجلد", category: "وثائق" },
  archive: { icon: Archive, label: "أرشيف", category: "وثائق" },
  download: { icon: Download, label: "تحميل", category: "وثائق" },
  gavel: { icon: Gavel, label: "قانون", category: "وثائق" },
  scale: { icon: Scale, label: "عدالة", category: "وثائق" },
  // — جغرافيا —
  countries: { icon: Globe, label: "دول", category: "جغرافيا" },
  globe: { icon: Globe2, label: "عالم", category: "جغرافيا" },
  earth: { icon: Earth, label: "كوكب", category: "جغرافيا" },
  mapPin: { icon: MapPin, label: "موقع", category: "جغرافيا" },
  map: { icon: Map, label: "خريطة", category: "جغرافيا" },
  compass: { icon: Compass, label: "بوصلة", category: "جغرافيا" },
  navigation: { icon: Navigation, label: "ملاحة", category: "جغرافيا" },
  flag: { icon: Flag, label: "علم", category: "جغرافيا" },
  // — نقل —
  truck: { icon: Truck, label: "شحن", category: "نقل" },
  package: { icon: Package, label: "طرود", category: "نقل" },
  plane: { icon: Plane, label: "طيران", category: "نقل" },
  ship: { icon: Ship, label: "شحن بحري", category: "نقل" },
  car: { icon: Car, label: "سيارة", category: "نقل" },
  bus: { icon: Bus, label: "حافلة", category: "نقل" },
  train: { icon: Train, label: "قطار", category: "نقل" },
  // — تواصل —
  mail: { icon: Mail, label: "بريد", category: "تواصل" },
  phone: { icon: Phone, label: "هاتف", category: "تواصل" },
  message: { icon: MessageCircle, label: "رسالة", category: "تواصل" },
  messages: { icon: MessagesSquare, label: "محادثات", category: "تواصل" },
  megaphone: { icon: Megaphone, label: "إعلان", category: "تواصل" },
  share: { icon: Share2, label: "مشاركة", category: "تواصل" },
  link: { icon: Link, label: "رابط", category: "تواصل" },
  // — وسائط —
  camera: { icon: Camera, label: "كاميرا", category: "وسائط" },
  image: { icon: Image, label: "صورة", category: "وسائط" },
  images: { icon: Images, label: "معرض", category: "وسائط" },
  video: { icon: Video, label: "فيديو", category: "وسائط" },
  play: { icon: Play, label: "تشغيل", category: "وسائط" },
  tv: { icon: Tv, label: "تلفاز", category: "وسائط" },
  party: { icon: PartyPopper, label: "احتفال", category: "وسائط" },
  // — غذاء —
  utensils: { icon: Utensils, label: "غذاء", category: "غذاء" },
  coffee: { icon: Coffee, label: "مشروبات", category: "غذاء" },
  apple: { icon: Apple, label: "فواكه", category: "غذاء" },
  wheat: { icon: Wheat, label: "حبوب", category: "غذاء" },
  milk: { icon: Milk, label: "ألبان", category: "غذاء" },
  campfire: { icon: Flame, label: "إمداد", category: "غذاء" },
  // — تقنية —
  wifi: { icon: Wifi, label: "إنترنت", category: "تقنية" },
  smartphone: { icon: Smartphone, label: "جوال", category: "تقنية" },
  laptop: { icon: Laptop, label: "حاسوب", category: "تقنية" },
  monitor: { icon: Monitor, label: "شاشة", category: "تقنية" },
  settings: { icon: Settings, label: "إعدادات", category: "تقنية" },
  lightbulb: { icon: Lightbulb, label: "فكرة", category: "تقنية" },
  zap: { icon: Zap, label: "طاقة", category: "تقنية" },
  // — عام —
  store: { icon: Store, label: "متجر", category: "عام" },
  cart: { icon: ShoppingCart, label: "تسوق", category: "عام" },
  box: { icon: Box, label: "صندوق", category: "عام" },
  layers: { icon: Layers, label: "طبقات", category: "عام" },
  grid: { icon: LayoutGrid, label: "شبكة", category: "عام" },
  briefcase: { icon: Briefcase, label: "أعمال", category: "عام" },
  crown: { icon: Crown, label: "قيادة", category: "عام" },
  userCheck: { icon: UserCheck, label: "تحقق", category: "عام" },
  userPlus: { icon: UserPlus, label: "انضمام", category: "عام" },
  lock: { icon: Lock, label: "أمان", category: "عام" },
  key: { icon: Key, label: "مفتاح", category: "عام" },
  recycle: { icon: Recycle, label: "استدامة", category: "عام" },
  help: { icon: HelpCircle, label: "مساعدة", category: "عام" },
  info: { icon: Info, label: "معلومات", category: "عام" },
  check: { icon: CheckCircle2, label: "تم", category: "عام" },
  plus: { icon: PlusCircle, label: "إضافة", category: "عام" },
};

export const iconCategories = [
  "الكل",
  "تنمية",
  "طبيعة",
  "تعليم",
  "صحة",
  "إنسانية",
  "تمويل",
  "عمليات",
  "تميز",
  "وثائق",
  "جغرافيا",
  "نقل",
  "تواصل",
  "وسائط",
  "غذاء",
  "تقنية",
  "عام",
] as const;

export function resolveCatalogIcon(key: string): LucideIcon {
  return iconCatalog[key]?.icon || iconCatalog.projects.icon;
}

export function getCatalogIconLabel(key: string): string {
  return iconCatalog[key]?.label || key;
}

/** كل الأيقونات للمنتقي */
export function getAllIconOptions() {
  return Object.entries(iconCatalog).map(([key, { icon, label, category }]) => ({
    key,
    label,
    icon,
    category,
  }));
}

/** خريطة للاستخدام في الموقع — دمج مع الأيقونات القديمة */
export function buildIconMap(): Record<string, LucideIcon> {
  const map: Record<string, LucideIcon> = {};
  for (const [key, entry] of Object.entries(iconCatalog)) {
    map[key] = entry.icon;
  }
  return map;
}
